# Generated by Django 5.2.1 on 2026-04-22 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sap_code', models.CharField(max_length=10, unique=True, verbose_name='Código Filial (SAP)')),
                ('state', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição Filial')),
                ('type', models.CharField(choices=[('warehouse', 'Armazém'), ('office', 'Escritório')], default='warehouse', max_length=20, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
                'ordering': ['sap_code'],
            },
        ),
        migrations.CreateModel(
            name='Corridor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Corredor',
                'verbose_name_plural': 'Corredores',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TerminalDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome Terminal')),
                ('sap_client_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Código SAP Cliente')),
                ('sap_supplier_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Código SAP Fornecedor')),
            ],
            options={
                'verbose_name': 'Terminal Destino',
                'verbose_name_plural': 'Terminais Destino',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommercialResponsible',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('state', models.CharField(blank=True, default='', max_length=2, verbose_name='Estado (UF)')),
                ('corporate_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone Corporativo')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_responsibles', to='core.branch', verbose_name='Filial alocado')),
            ],
            options={
                'verbose_name': 'Comercial Responsável',
                'verbose_name_plural': 'Comerciais Responsáveis',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome Participante')),
                ('sap_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Código SAP')),
                ('inscricao_estadual', models.CharField(blank=True, default='', max_length=30, verbose_name='Inscrição Estadual')),
                ('cnpj', models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cnpj', ''), _negated=True), fields=('cnpj',), name='participant_unique_cnpj')],
            },
        ),
        migrations.CreateModel(
            name='TransshipmentLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transshipment_locations', to='core.branch')),
            ],
            options={
                'verbose_name': 'Local de Transbordo',
                'verbose_name_plural': 'Locais de Transbordo',
                'ordering': ['name'],
            },
        ),
    ]
