# Generated by Django 5.2.1 on 2026-04-27 20:52

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transportadora_historicaltransportadora_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportadoraALZT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sap_code', models.CharField(max_length=10, unique=True, verbose_name='Código Filial (SAP)')),
                ('state', models.CharField(blank=True, default='', max_length=2, verbose_name='Estado (UF)')),
                ('cnpj', models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Transportadora ALZT',
                'verbose_name_plural': 'Transportadoras ALZT',
                'ordering': ['sap_code'],
            },
        ),
        migrations.AddField(
            model_name='historicalterminaldestination',
            name='customs_facility_code',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Código Recinto Alfandegado'),
        ),
        migrations.AddField(
            model_name='historicalterminaldestination',
            name='is_transshipment',
            field=models.BooleanField(default=False, verbose_name='Local de transbordo?'),
        ),
        migrations.AddField(
            model_name='historicaltransportadora',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='historicaltransportadora',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='historicaltransportadora',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone Celular'),
        ),
        migrations.AddField(
            model_name='terminaldestination',
            name='customs_facility_code',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Código Recinto Alfandegado'),
        ),
        migrations.AddField(
            model_name='terminaldestination',
            name='is_transshipment',
            field=models.BooleanField(default=False, verbose_name='Local de transbordo?'),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone Celular'),
        ),
        migrations.AlterField(
            model_name='historicaltransportadora',
            name='code',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Código SAP Fornecedor'),
        ),
        migrations.AlterField(
            model_name='historicaltransportadora',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome Transportadora'),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código SAP Fornecedor'),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome Transportadora'),
        ),
        migrations.CreateModel(
            name='HistoricalTransportadoraALZT',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('sap_code', models.CharField(db_index=True, max_length=10, verbose_name='Código Filial (SAP)')),
                ('state', models.CharField(blank=True, default='', max_length=2, verbose_name='Estado (UF)')),
                ('cnpj', models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Transportadora ALZT',
                'verbose_name_plural': 'historical Transportadoras ALZT',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
