# Generated by Django 5.2.1 on 2026-05-05 15:08 (rewritten to use RenameModel)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transportadoraalzt_and_more'),
    ]

    operations = [
        # Rename TipoFreteSaida -> ExitFreightType (preserves all existing rows)
        migrations.RenameModel(old_name='TipoFreteSaida', new_name='ExitFreightType'),
        migrations.RenameModel(old_name='HistoricalTipoFreteSaida', new_name='HistoricalExitFreightType'),
        # Add new fields to the renamed model
        migrations.AddField(
            model_name='exitfreighttype',
            name='incoterm',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Incoterm'),
        ),
        migrations.AddField(
            model_name='exitfreighttype',
            name='loc_incoterm',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Incoterm local'),
        ),
        migrations.AddField(
            model_name='historicalexitfreighttype',
            name='incoterm',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Incoterm'),
        ),
        migrations.AddField(
            model_name='historicalexitfreighttype',
            name='loc_incoterm',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Incoterm local'),
        ),
        # Rename Carrier models
        migrations.RenameModel(old_name='Transportadora', new_name='Carrier'),
        migrations.RenameModel(old_name='TransportadoraALZT', new_name='CarrierALZT'),
        migrations.RenameModel(old_name='HistoricalTransportadora', new_name='HistoricalCarrier'),
        migrations.RenameModel(old_name='HistoricalTransportadoraALZT', new_name='HistoricalCarrierALZT'),
    ]
