# Generated by Django 5.2.1 on 2026-05-05 15:08 (no-op: cleanup handled by 0007)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_alter_contractmanagedlot_freight_type_exit_and_more'),
        ('core', '0007_exitfreighttype_historicalexitfreighttype_and_more'),
        ('orders', '0005_remove_historicalsalesorder_ov_solicitation_number_and_more'),
    ]

    operations = [
    ]
