# Generated by Django 5.2.1 on 2026-05-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_tipofretesaida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitfreighttype',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='exitfreighttype',
            name='description_short',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Descrição Rápida'),
        ),
        migrations.AddField(
            model_name='historicalexitfreighttype',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='historicalexitfreighttype',
            name='description_short',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Descrição Rápida'),
        ),
        migrations.AlterField(
            model_name='exitfreighttype',
            name='loc_incoterm',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Incoterm local'),
        ),
        migrations.AlterField(
            model_name='historicalexitfreighttype',
            name='loc_incoterm',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Incoterm local'),
        ),
    ]
