# Generated by Django 5.2.1 on 2026-05-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_exitfreighttype_descriptions_managedlot_billing_branch_nf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitfreighttype',
            name='incoterm',
            field=models.CharField(default='', max_length=10, verbose_name='Incoterm'),
        ),
        migrations.AlterField(
            model_name='exitfreighttype',
            name='loc_incoterm',
            field=models.CharField(default='', max_length=50, verbose_name='Incoterm local'),
        ),
        migrations.AlterField(
            model_name='historicalexitfreighttype',
            name='incoterm',
            field=models.CharField(default='', max_length=10, verbose_name='Incoterm'),
        ),
        migrations.AlterField(
            model_name='historicalexitfreighttype',
            name='loc_incoterm',
            field=models.CharField(default='', max_length=50, verbose_name='Incoterm local'),
        ),
        migrations.AlterField(
            model_name='historicalparticipant',
            name='cnpj',
            field=models.CharField(default='', max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='historicalterminaldestination',
            name='customs_facility_code',
            field=models.CharField(default='', max_length=30, verbose_name='Código Recinto Alfandegado'),
        ),
        migrations.AlterField(
            model_name='historicalterminaldestination',
            name='sap_client_code',
            field=models.CharField(default='', max_length=20, verbose_name='Código SAP Cliente'),
        ),
        migrations.AlterField(
            model_name='historicalterminaldestination',
            name='sap_supplier_code',
            field=models.CharField(default='', max_length=20, verbose_name='Código SAP Fornecedor'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='cnpj',
            field=models.CharField(default='', max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='terminaldestination',
            name='customs_facility_code',
            field=models.CharField(default='', max_length=30, verbose_name='Código Recinto Alfandegado'),
        ),
        migrations.AlterField(
            model_name='terminaldestination',
            name='sap_client_code',
            field=models.CharField(default='', max_length=20, verbose_name='Código SAP Cliente'),
        ),
        migrations.AlterField(
            model_name='terminaldestination',
            name='sap_supplier_code',
            field=models.CharField(default='', max_length=20, verbose_name='Código SAP Fornecedor'),
        ),
    ]
