# Generated by Django 5.2.1 on 2026-04-22 21:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_contractmanagedlot_corridor'),
        ('core', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ov_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Nº OV')),
                ('ov_solicitation_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Nº solicitação SAP')),
                ('ov_status', models.CharField(choices=[('pending', 'Aguardando criação'), ('in_progress', 'Em andamento'), ('closed', 'Encerrado'), ('paused', 'Paralisado')], default='pending', max_length=20, verbose_name='Status OV')),
                ('rpa_status', models.CharField(choices=[('awaiting_ov_creation', 'Aguardando criação OV'), ('executing', 'Executando'), ('awaiting_approval', 'Aguardando aprovação SAP'), ('completed', 'Criado'), ('rejected', 'Rejeitado'), ('error', 'Erro'), ('na', 'Não se aplica')], default='awaiting_ov_creation', max_length=30, verbose_name='Status RPA')),
                ('rpa_error_message', models.TextField(blank=True, default='', verbose_name='Erro RPA')),
                ('rpa_last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Última tentativa RPA')),
                ('rpa_retry_count', models.PositiveIntegerField(default=0, verbose_name='Tentativas RPA')),
                ('creation_event_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Data evento criação')),
                ('total_quantity_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Qtd total OV (kg)')),
                ('delivered_quantity_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Qtd entregue (kg)')),
                ('balance_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Saldo (kg)')),
                ('cadence', models.CharField(blank=True, default='', max_length=50, verbose_name='Cadência')),
                ('exit_freight_type', models.CharField(blank=True, default='', max_length=10, verbose_name='Tipo frete saída')),
                ('rfl_value_kg', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Valor RFL (R$/kg)')),
                ('freight_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor frete')),
                ('billing_producer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome produtor faturamento')),
                ('client_state_registration', models.CharField(blank=True, default='', max_length=20, verbose_name='Inscrição estadual cliente')),
                ('order_index', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data encerramento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_sales_orders', to='core.branch', verbose_name='Filial faturamento')),
                ('managed_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='contracts.contractmanagedlot', verbose_name='Lote')),
                ('nf_future_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='invoices.nffuturedelivery', verbose_name='NF Entrega Futura')),
                ('terminal_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='core.terminaldestination', verbose_name='Terminal destino')),
                ('transshipment_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='core.transshipmentlocation', verbose_name='Local transbordo')),
            ],
            options={
                'verbose_name': 'Ordem de Venda',
                'verbose_name_plural': 'Ordens de Venda',
                'ordering': ['managed_lot', 'order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoadingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oc_number', models.CharField(max_length=20, verbose_name='Nº OC')),
                ('plate', models.CharField(blank=True, default='', max_length=10, verbose_name='Placa')),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Peso (kg)')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('inactive', 'Inativa')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Data vencimento')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_orders', to='orders.salesorder', verbose_name='Ordem de venda')),
            ],
            options={
                'verbose_name': 'Ordem de Carregamento',
                'verbose_name_plural': 'Ordens de Carregamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
