# Generated by Django 5.2.1 on 2026-04-23 13:35

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_historicalcontractbaselot_and_more'),
        ('core', '0002_historicalbranch_historicalcommercialresponsible_and_more'),
        ('invoices', '0002_historicalnffuturedelivery'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLoadingOrder',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('oc_number', models.CharField(max_length=20, verbose_name='Nº OC')),
                ('plate', models.CharField(blank=True, default='', max_length=10, verbose_name='Placa')),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Peso (kg)')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('inactive', 'Inativa')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Data vencimento')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.salesorder', verbose_name='Ordem de venda')),
            ],
            options={
                'verbose_name': 'historical Ordem de Carregamento',
                'verbose_name_plural': 'historical Ordens de Carregamento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSalesOrder',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('ov_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Nº OV')),
                ('ov_solicitation_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Nº solicitação SAP')),
                ('ov_status', models.CharField(choices=[('pending', 'Aguardando criação'), ('in_progress', 'Em andamento'), ('closed', 'Encerrado'), ('paused', 'Paralisado')], default='pending', max_length=20, verbose_name='Status OV')),
                ('rpa_status', models.CharField(choices=[('awaiting_ov_creation', 'Aguardando criação OV'), ('executing', 'Executando'), ('awaiting_approval', 'Aguardando aprovação SAP'), ('completed', 'Criado'), ('rejected', 'Rejeitado'), ('error', 'Erro'), ('na', 'Não se aplica')], default='awaiting_ov_creation', max_length=30, verbose_name='Status RPA')),
                ('rpa_error_message', models.TextField(blank=True, default='', verbose_name='Erro RPA')),
                ('rpa_last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Última tentativa RPA')),
                ('rpa_retry_count', models.PositiveIntegerField(default=0, verbose_name='Tentativas RPA')),
                ('creation_event_datetime', models.DateTimeField(blank=True, editable=False, verbose_name='Data evento criação')),
                ('total_quantity_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Qtd total OV (kg)')),
                ('delivered_quantity_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Qtd entregue (kg)')),
                ('balance_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Saldo (kg)')),
                ('cadence', models.CharField(blank=True, default='', max_length=50, verbose_name='Cadência')),
                ('exit_freight_type', models.CharField(blank=True, default='', max_length=10, verbose_name='Tipo frete saída')),
                ('rfl_value_kg', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Valor RFL (R$/kg)')),
                ('freight_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor frete')),
                ('billing_producer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome produtor faturamento')),
                ('client_state_registration', models.CharField(blank=True, default='', max_length=20, verbose_name='Inscrição estadual cliente')),
                ('order_index', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data encerramento')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('billing_branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.branch', verbose_name='Filial faturamento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('managed_lot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contracts.contractmanagedlot', verbose_name='Lote')),
                ('nf_future_delivery', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='invoices.nffuturedelivery', verbose_name='NF Entrega Futura')),
                ('terminal_destination', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.terminaldestination', verbose_name='Terminal destino')),
                ('transshipment_location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.transshipmentlocation', verbose_name='Local transbordo')),
            ],
            options={
                'verbose_name': 'historical Ordem de Venda',
                'verbose_name_plural': 'historical Ordens de Venda',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
