# Generated by Django 5.2.1 on 2026-04-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_historicalloadingorder_historicalsalesorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalesorder',
            name='manually_created',
            field=models.BooleanField(default=False, help_text='OV registrada manualmente no portal, sem passar pelo RPA.', verbose_name='Criada manualmente'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='manually_created',
            field=models.BooleanField(default=False, help_text='OV registrada manualmente no portal, sem passar pelo RPA.', verbose_name='Criada manualmente'),
        ),
    ]
