# Generated by Django 5.2.1 on 2026-04-27 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transportadoraalzt_and_more'),
        ('orders', '0003_historicalsalesorder_manually_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsalesorder',
            name='exit_freight_type',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='exit_freight_type',
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='alternative_route',
            field=models.BooleanField(default=False, verbose_name='Percurso Alternativo'),
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='collection_point_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Código Ponto de Coleta'),
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='corridor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.corridor', verbose_name='Corredor'),
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='freight_agent',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Agente Frete'),
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='freight_type_exit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tipofretesaida', verbose_name='Tipo Frete Saída'),
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='harvest_year',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Safra'),
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Invalidada em'),
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='invalidated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Invalidada por'),
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='original_order',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Preenchido quando esta OV é uma revisão de outra. Aponta para a OV raíz.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.salesorder', verbose_name='OV original'),
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='product_sap_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Código SAP Produto'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='alternative_route',
            field=models.BooleanField(default=False, verbose_name='Percurso Alternativo'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='collection_point_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Código Ponto de Coleta'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='corridor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='core.corridor', verbose_name='Corredor'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='freight_agent',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Agente Frete'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='freight_type_exit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='core.tipofretesaida', verbose_name='Tipo Frete Saída'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='harvest_year',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Safra'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Invalidada em'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invalidated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invalidated_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='Invalidada por'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='original_order',
            field=models.ForeignKey(blank=True, help_text='Preenchido quando esta OV é uma revisão de outra. Aponta para a OV raíz.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='orders.salesorder', verbose_name='OV original'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='product_sap_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Código SAP Produto'),
        ),
        migrations.AlterField(
            model_name='historicalsalesorder',
            name='ov_status',
            field=models.CharField(choices=[('pending', 'Aguardando criação'), ('in_progress', 'Em andamento'), ('closed', 'Encerrado'), ('paused', 'Paralisado'), ('invalidated', 'Invalidada')], default='pending', max_length=20, verbose_name='Status OV'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ov_status',
            field=models.CharField(choices=[('pending', 'Aguardando criação'), ('in_progress', 'Em andamento'), ('closed', 'Encerrado'), ('paused', 'Paralisado'), ('invalidated', 'Invalidada')], default='pending', max_length=20, verbose_name='Status OV'),
        ),
    ]
