# Generated by Django 5.2.1 on 2026-05-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_exitfreighttype_historicalexitfreighttype_and_more'),
        ('orders', '0004_remove_historicalsalesorder_exit_freight_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsalesorder',
            name='ov_solicitation_number',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='ov_solicitation_number',
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='external_rpa_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID externo RPA'),
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='rpa_error_type',
            field=models.CharField(blank=True, choices=[('business_exception', 'Exceção de negócio'), ('system_exception', 'Exceção de sistema')], default='', max_length=20, verbose_name='Tipo erro RPA'),
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='rpa_screenshot',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Screenshot RPA'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='external_rpa_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID externo RPA'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='rpa_error_type',
            field=models.CharField(blank=True, choices=[('business_exception', 'Exceção de negócio'), ('system_exception', 'Exceção de sistema')], default='', max_length=20, verbose_name='Tipo erro RPA'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='rpa_screenshot',
            field=models.FileField(blank=True, null=True, upload_to='rpa_screenshots/', verbose_name='Screenshot RPA'),
        ),
        migrations.AlterField(
            model_name='historicalsalesorder',
            name='freight_type_exit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.exitfreighttype', verbose_name='Tipo Frete Saída'),
        ),
        migrations.AlterField(
            model_name='historicalsalesorder',
            name='rpa_status',
            field=models.CharField(choices=[('awaiting_ov_creation', 'Aguardando criação OV'), ('executing', 'Executando'), ('completed', 'Criado'), ('error', 'Erro'), ('na', 'Não se aplica'), ('awaiting_ov_quantity_update', 'Aguardando atualização quantidade OV')], default='awaiting_ov_creation', max_length=30, verbose_name='Status RPA'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='freight_type_exit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='core.exitfreighttype', verbose_name='Tipo Frete Saída'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='rpa_status',
            field=models.CharField(choices=[('awaiting_ov_creation', 'Aguardando criação OV'), ('executing', 'Executando'), ('completed', 'Criado'), ('error', 'Erro'), ('na', 'Não se aplica'), ('awaiting_ov_quantity_update', 'Aguardando atualização quantidade OV')], default='awaiting_ov_creation', max_length=30, verbose_name='Status RPA'),
        ),
    ]
