# Generated by Django 5.2.1 on 2026-05-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_historicalsalesorder_ov_solicitation_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalesorder',
            name='rpa_traceback',
            field=models.TextField(blank=True, default='', verbose_name='Traceback RPA'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='rpa_traceback',
            field=models.TextField(blank=True, default='', verbose_name='Traceback RPA'),
        ),
    ]
