# Generated by Django 5.2.1 on 2026-04-22 21:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalInstruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('harvest_year', models.CharField(max_length=4, verbose_name='Safra')),
                ('product', models.CharField(max_length=50, verbose_name='Produto')),
                ('person_type', models.CharField(choices=[('PF', 'Pessoa física'), ('PJ', 'Pessoa jurídica')], max_length=2, verbose_name='Tipo pessoa')),
                ('issuer_state', models.CharField(max_length=2, verbose_name='UF emitente')),
                ('has_nf_future_delivery', models.BooleanField(default=False, verbose_name='Possui NF entrega futura')),
                ('instruction_text', models.TextField(blank=True, default='', verbose_name='Orientação')),
                ('destination', models.CharField(blank=True, default='', max_length=200, verbose_name='Destino')),
                ('freight_value', models.CharField(blank=True, default='', max_length=100, verbose_name='Valor frete')),
                ('route_description', models.TextField(blank=True, default='', verbose_name='Roteiro')),
                ('client_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Cliente')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_instructions', to='core.branch', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Instrução fiscal',
                'verbose_name_plural': 'Instruções fiscais',
                'ordering': ['branch', 'harvest_year', 'product'],
                'indexes': [models.Index(fields=['branch', 'harvest_year', 'product', 'person_type', 'issuer_state', 'has_nf_future_delivery'], name='fisc_inst_lookup_idx')],
            },
        ),
    ]
