# Generated by Django 5.2.1 on 2026-04-23 13:35

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalbranch_historicalcommercialresponsible_and_more'),
        ('fiscal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFiscalInstruction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('harvest_year', models.CharField(max_length=4, verbose_name='Safra')),
                ('product', models.CharField(max_length=50, verbose_name='Produto')),
                ('person_type', models.CharField(choices=[('PF', 'Pessoa física'), ('PJ', 'Pessoa jurídica')], max_length=2, verbose_name='Tipo pessoa')),
                ('issuer_state', models.CharField(max_length=2, verbose_name='UF emitente')),
                ('has_nf_future_delivery', models.BooleanField(default=False, verbose_name='Possui NF entrega futura')),
                ('instruction_text', models.TextField(blank=True, default='', verbose_name='Orientação')),
                ('destination', models.CharField(blank=True, default='', max_length=200, verbose_name='Destino')),
                ('freight_value', models.CharField(blank=True, default='', max_length=100, verbose_name='Valor frete')),
                ('route_description', models.TextField(blank=True, default='', verbose_name='Roteiro')),
                ('client_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Cliente')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.branch', verbose_name='Filial')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Instrução fiscal',
                'verbose_name_plural': 'historical Instruções fiscais',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
