# Generated by Django 5.2.1 on 2026-04-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0002_historicalfiscalinstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalinstruction',
            name='instruction_name',
            field=models.CharField(blank=True, default='', help_text='Título exibido ao usuário, ex.: "IT Diferimento PI".', max_length=255, verbose_name='Nome da instrução'),
        ),
        migrations.AddField(
            model_name='fiscalinstruction',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Documento anexado à instrução, disponível para download.', null=True, upload_to='fiscal_instructions/', verbose_name='Arquivo PDF'),
        ),
        migrations.AddField(
            model_name='historicalfiscalinstruction',
            name='instruction_name',
            field=models.CharField(blank=True, default='', help_text='Título exibido ao usuário, ex.: "IT Diferimento PI".', max_length=255, verbose_name='Nome da instrução'),
        ),
        migrations.AddField(
            model_name='historicalfiscalinstruction',
            name='pdf_file',
            field=models.TextField(blank=True, help_text='Documento anexado à instrução, disponível para download.', max_length=100, null=True, verbose_name='Arquivo PDF'),
        ),
    ]
