# Generated by Django 5.2.1 on 2026-04-17 18:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'Um usuário com este email já existe.'}, max_length=254, unique=True, verbose_name='endereço de email')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'Formato inválido. O telefone deve ter 13 dígitos (55 + DDD + 9 números).')], verbose_name='número de telefone')),
                ('is_internal_staff', models.BooleanField(default=False, help_text='Designa se este usuário é da equipe interna da ALZ.', verbose_name='equipe interna')),
                ('microsoft_oauth_uid', models.CharField(blank=True, help_text='Identificador único do OAuth Microsoft', max_length=255, null=True, unique=True, verbose_name='UID OAuth Microsoft')),
                ('force_password_change', models.BooleanField(default=False, help_text='Usuário deve alterar a senha no próximo login', verbose_name='forçar mudança de senha')),
                ('password_changed_at', models.DateTimeField(blank=True, help_text='Data e hora da última alteração de senha', null=True, verbose_name='senha alterada em')),
                ('password_reset_token', models.UUIDField(blank=True, help_text='Token para redefinição de senha', null=True, verbose_name='token de redefinição de senha')),
                ('password_reset_expires', models.DateTimeField(blank=True, help_text='Data e hora de expiração do token de redefinição de senha', null=True, verbose_name='expiração do token de redefinição')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='Endereço IP do último login', null=True, verbose_name='IP do último login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'auth_users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InternalUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('COMERCIAL', 'Comercial'), ('LOGISTICS', 'Logística'), ('FISCAL', 'Fiscal'), ('ADMIN', 'Administrador')], max_length=50, verbose_name='perfil')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_roles', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Perfil Interno',
                'verbose_name_plural': 'Perfis Internos',
                'db_table': 'auth_internal_user_roles',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='auth_users_email_9c7e62_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='auth_users_usernam_36e497_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['microsoft_oauth_uid'], name='auth_users_microso_77830a_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active', 'is_internal_staff'], name='auth_users_is_acti_45f9aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='internaluserrole',
            unique_together={('user', 'role')},
        ),
    ]
