# Generated by Django 5.2.1 on 2026-04-22 21:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFFutureDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nf_number', models.CharField(max_length=20, verbose_name='Nº NF')),
                ('nf_key', models.CharField(blank=True, default='', max_length=44, verbose_name='Chave NF')),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Qtd NF (kg)')),
                ('unit_value', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Valor unitário')),
                ('gross_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor bruto')),
                ('branch_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Filial')),
                ('product', models.CharField(blank=True, default='', max_length=50, verbose_name='Produto')),
                ('harvest_year', models.CharField(blank=True, default='', max_length=4, verbose_name='Safra')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Data emissão')),
                ('sap_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Código SAP')),
                ('state_registration', models.CharField(blank=True, default='', max_length=20, verbose_name='Inscrição estadual')),
                ('lot_number', models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='Nº Lote')),
                ('producer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome produtor')),
                ('status', models.CharField(choices=[('in_progress', 'Em andamento'), ('finished', 'Finalizada')], default='in_progress', max_length=20, verbose_name='Status')),
                ('delivered_quantity_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Qtd entregue (kg)')),
                ('remaining_quantity_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Saldo (kg)')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='nf_future_delivery/%Y/%m/', verbose_name='Arquivo XML')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NF Entrega Futura',
                'verbose_name_plural': 'NFs Entrega Futura',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
