# Generated by Django 5.2.1 on 2026-04-23 13:35

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNFFutureDelivery',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('nf_number', models.CharField(max_length=20, verbose_name='Nº NF')),
                ('nf_key', models.CharField(blank=True, default='', max_length=44, verbose_name='Chave NF')),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Qtd NF (kg)')),
                ('unit_value', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Valor unitário')),
                ('gross_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor bruto')),
                ('branch_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Filial')),
                ('product', models.CharField(blank=True, default='', max_length=50, verbose_name='Produto')),
                ('harvest_year', models.CharField(blank=True, default='', max_length=4, verbose_name='Safra')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Data emissão')),
                ('sap_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Código SAP')),
                ('state_registration', models.CharField(blank=True, default='', max_length=20, verbose_name='Inscrição estadual')),
                ('lot_number', models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='Nº Lote')),
                ('producer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome produtor')),
                ('status', models.CharField(choices=[('in_progress', 'Em andamento'), ('finished', 'Finalizada')], default='in_progress', max_length=20, verbose_name='Status')),
                ('delivered_quantity_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Qtd entregue (kg)')),
                ('remaining_quantity_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Saldo (kg)')),
                ('xml_file', models.TextField(blank=True, max_length=100, null=True, verbose_name='Arquivo XML')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical NF Entrega Futura',
                'verbose_name_plural': 'historical NFs Entrega Futura',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
