# Generated by Django 5.2.1 on 2026-04-23 18:02

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_historicalnffuturedelivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFValidationError',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Código')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Nível 1 (NFref)'), (2, 'Nível 2 (IE)'), (3, 'Nível 3 (OV chain)')], verbose_name='Nível')),
                ('message_pt', models.CharField(max_length=255, verbose_name='Mensagem PT-BR')),
                ('detail_pt', models.TextField(blank=True, default='', verbose_name='Detalhe PT-BR')),
                ('recommended_action', models.TextField(blank=True, default='', verbose_name='Ação recomendada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Erro de validação de NF',
                'verbose_name_plural': 'Erros de validação de NF',
                'ordering': ['level', 'code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalChildNF',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('nf_number', models.CharField(db_index=True, max_length=20, verbose_name='Nº NF filha')),
                ('nf_key', models.CharField(blank=True, db_index=True, default='', max_length=44, verbose_name='Chave NF')),
                ('serie', models.CharField(blank=True, default='', max_length=10, verbose_name='Série')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Data emissão')),
                ('emitter_cnpj', models.CharField(blank=True, default='', max_length=20, verbose_name='CNPJ emitente')),
                ('emitter_state_registration', models.CharField(blank=True, default='', max_length=20, verbose_name='IE emitente')),
                ('quantity_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Qtd (kg)')),
                ('unit_value', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Valor unitário')),
                ('validation_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nível atingido')),
                ('validation_status', models.CharField(choices=[('pending', 'Aguardando validação'), ('valid', 'Validada'), ('invalid', 'Não validada'), ('needs_review', 'Revisão manual')], db_index=True, default='pending', max_length=20, verbose_name='Status validação')),
                ('validation_detail', models.TextField(blank=True, default='', verbose_name='Detalhe validação')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validado em')),
                ('has_correction_letter', models.BooleanField(default=False, verbose_name='Possui Carta de Correção')),
                ('correction_new_mother_ref', models.CharField(blank=True, default='', max_length=44, verbose_name='Nova referência da CC')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mother_nf', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='invoices.nffuturedelivery', verbose_name='NF mãe')),
                ('validation_error', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='invoices.nfvalidationerror', verbose_name='Erro de validação')),
            ],
            options={
                'verbose_name': 'historical NF filha',
                'verbose_name_plural': 'historical NFs filhas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ChildNF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nf_number', models.CharField(db_index=True, max_length=20, verbose_name='Nº NF filha')),
                ('nf_key', models.CharField(blank=True, db_index=True, default='', max_length=44, verbose_name='Chave NF')),
                ('serie', models.CharField(blank=True, default='', max_length=10, verbose_name='Série')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Data emissão')),
                ('emitter_cnpj', models.CharField(blank=True, default='', max_length=20, verbose_name='CNPJ emitente')),
                ('emitter_state_registration', models.CharField(blank=True, default='', max_length=20, verbose_name='IE emitente')),
                ('quantity_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Qtd (kg)')),
                ('unit_value', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Valor unitário')),
                ('validation_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nível atingido')),
                ('validation_status', models.CharField(choices=[('pending', 'Aguardando validação'), ('valid', 'Validada'), ('invalid', 'Não validada'), ('needs_review', 'Revisão manual')], db_index=True, default='pending', max_length=20, verbose_name='Status validação')),
                ('validation_detail', models.TextField(blank=True, default='', verbose_name='Detalhe validação')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validado em')),
                ('has_correction_letter', models.BooleanField(default=False, verbose_name='Possui Carta de Correção')),
                ('correction_new_mother_ref', models.CharField(blank=True, default='', max_length=44, verbose_name='Nova referência da CC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mother_nf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='invoices.nffuturedelivery', verbose_name='NF mãe')),
                ('validation_error', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_nfs', to='invoices.nfvalidationerror', verbose_name='Erro de validação')),
            ],
            options={
                'verbose_name': 'NF filha',
                'verbose_name_plural': 'NFs filhas',
                'ordering': ['-issue_date', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('nf_key', ''), _negated=True), fields=('nf_key',), name='childnf_unique_nf_key_when_present')],
            },
        ),
    ]
