# Generated by Django 5.2.1 on 2026-04-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_nfvalidationerror_historicalchildnf_childnf'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nffuturedelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('lot_number', ''), _negated=True), fields=('lot_number',), name='nf_mother_unique_lot_number_when_present'),
        ),
    ]
