# Generated by Django 5.2.1 on 2026-04-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_nffuturedelivery_nf_mother_unique_lot_number_when_present'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nffuturedelivery',
            name='nf_mother_unique_lot_number_when_present',
        ),
    ]
