# Generated by Django 5.2.1 on 2026-04-27 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_nffuturedelivery_nf_mother_unique_lot_number_when_present'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='childnf',
            name='xml_file',
            field=models.FileField(blank=True, null=True, upload_to='child_nf/%Y/%m/', verbose_name='Arquivo XML'),
        ),
        migrations.AddField(
            model_name='historicalchildnf',
            name='xml_file',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Arquivo XML'),
        ),
        migrations.CreateModel(
            name='NFXmlFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('mother', 'NF mãe'), ('child', 'NF filha'), ('cce', 'Carta de correção'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Tipo')),
                ('nf_key', models.CharField(blank=True, db_index=True, default='', max_length=44, verbose_name='Chave NF')),
                ('nf_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Nº NF')),
                ('file', models.FileField(upload_to='nf_xml/%Y/%m/', verbose_name='Arquivo')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome original')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('source', models.CharField(blank=True, default='', help_text='portal, rpa, ocr, nfe_key, ...', max_length=30, verbose_name='Origem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_nf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xml_files', to='invoices.childnf', verbose_name='NF filha')),
                ('mother_nf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xml_files', to='invoices.nffuturedelivery', verbose_name='NF mãe')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nf_xml_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Arquivo XML de NF',
                'verbose_name_plural': 'Arquivos XML de NF',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nf_key'], name='invoices_nf_nf_key_6f9037_idx'), models.Index(fields=['nf_number'], name='invoices_nf_nf_numb_977052_idx')],
            },
        ),
    ]
