# Generated by Django 5.2.1 on 2026-04-23 17:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RpaDispatchTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('fiscal_instruction_email', 'Envio de instrução fiscal (e-mail)'), ('fiscal_instruction_whatsapp', 'Envio de instrução fiscal (WhatsApp)'), ('desk_manager_ticket', 'Abertura de chamado Desk Manager')], db_index=True, max_length=40, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em execução'), ('completed', 'Concluído'), ('error', 'Erro')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('related_object_type', models.CharField(blank=True, choices=[('fiscal_instruction', 'Instrução fiscal'), ('sales_order', 'Ordem de venda'), ('shipment_request', 'Solicitação de embarque')], default='', max_length=40, verbose_name='Tipo do objeto')),
                ('related_object_id', models.UUIDField(blank=True, null=True, verbose_name='ID do objeto')),
                ('external_reference', models.CharField(blank=True, default='', help_text='Nº do chamado / id da mensagem retornado pelo RPA.', max_length=100, verbose_name='Referência externa')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensagem de erro')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Última tentativa')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
            ],
            options={
                'verbose_name': 'Tarefa RPA',
                'verbose_name_plural': 'Tarefas RPA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'task_type'], name='rpa_dispatc_status_585ef3_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='rpa_dispatc_related_0ab2cb_idx')],
            },
        ),
    ]
