# Generated by Django 5.2.1 on 2026-04-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpadispatchtask',
            name='related_object_type',
            field=models.CharField(blank=True, choices=[('fiscal_instruction', 'Instrução fiscal'), ('sales_order', 'Ordem de venda'), ('shipment_request', 'Solicitação de embarque'), ('child_nf', 'NF filha')], default='', max_length=40, verbose_name='Tipo do objeto'),
        ),
        migrations.AlterField(
            model_name='rpadispatchtask',
            name='task_type',
            field=models.CharField(choices=[('fiscal_instruction_email', 'Envio de instrução fiscal (e-mail)'), ('fiscal_instruction_whatsapp', 'Envio de instrução fiscal (WhatsApp)'), ('desk_manager_ticket', 'Abertura de chamado Desk Manager'), ('nf_correction_reprocess', 'Reprocessar NF após carta de correção')], db_index=True, max_length=40, verbose_name='Tipo'),
        ),
    ]
