# Generated by Django 5.2.1 on 2026-04-22 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractBaseLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpf_cnpj', models.CharField(blank=True, default='', max_length=20, verbose_name='CPF/CNPJ')),
                ('liquidity', models.CharField(blank=True, default='', max_length=100, verbose_name='Liquidez')),
                ('branch_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Filial')),
                ('producer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Produtor')),
                ('lot_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Tipo Lote')),
                ('product', models.CharField(blank=True, default='', max_length=100, verbose_name='Produto')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade')),
                ('state_code', models.CharField(blank=True, default='', max_length=10, verbose_name='UF')),
                ('lot_number', models.CharField(db_index=True, max_length=30, verbose_name='Nº Lote')),
                ('quantity_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Quantidade (KG)')),
                ('delivered_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Entregue (KG)')),
                ('reversed_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Qtde Estornada (KG)')),
                ('remaining_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='A entregar (KG)')),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Saldo')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data pagamento')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Preço')),
                ('freight_type', models.CharField(blank=True, default='', max_length=10, verbose_name='Tipo Frete')),
                ('freight_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Vr. Frete')),
                ('emits_re', models.BooleanField(default=False, verbose_name='Emite RE')),
                ('purchase_desk_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Id Compra Mesa')),
                ('address_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Cód. Endereço')),
                ('product_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo Produto')),
                ('unit_value', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Unitário')),
                ('lot_date', models.DateField(blank=True, null=True, verbose_name='Data lote')),
                ('dap', models.CharField(blank=True, default='', max_length=50, verbose_name='DAP')),
                ('load_producer', models.CharField(blank=True, default='', max_length=200, verbose_name='Produtor Embarque')),
                ('load_location', models.CharField(blank=True, default='', max_length=300, verbose_name='Local de Embarque')),
                ('load_city', models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade Embarque')),
                ('load_state', models.CharField(blank=True, default='', max_length=10, verbose_name='UF Embarque')),
                ('cpf_cnpj_load', models.CharField(blank=True, default='', max_length=20, verbose_name='CPF/CNPJ Embarque')),
                ('delivery_start_date', models.DateField(blank=True, null=True, verbose_name='Dt Início Entrega')),
                ('delivery_end_date', models.DateField(blank=True, null=True, verbose_name='Dt Final Entrega')),
                ('destination_branch', models.CharField(blank=True, default='', max_length=100, verbose_name='Filial Destino')),
                ('currency', models.CharField(blank=True, default='', max_length=10, verbose_name='Moeda')),
            ],
            options={
                'verbose_name': 'Lote Base',
                'verbose_name_plural': 'Lotes Base',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractManagedLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('awaiting_request', 'Aguardando solicitação de embarque'), ('awaiting_approval', 'Aguardando liberação'), ('in_progress', 'Embarque em andamento'), ('finished', 'Embarque Finalizado'), ('cancelled', 'Cancelado')], default='awaiting_request', max_length=30, verbose_name='Status')),
                ('shipment_released', models.BooleanField(default=False, verbose_name='Embarque Liberado')),
                ('harvest_year', models.CharField(blank=True, default='', max_length=10, verbose_name='Safra')),
                ('pickup_location', models.CharField(blank=True, default='', max_length=300, verbose_name='Local Retirada')),
                ('region', models.CharField(blank=True, default='', max_length=100, verbose_name='Região')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('route_description', models.TextField(blank=True, default='', verbose_name='Roteiro')),
                ('scale_over_25m', models.BooleanField(default=False, verbose_name='Balança > 25m')),
                ('silo_bag_loading', models.BooleanField(default=False, verbose_name='Carregamento silo bolsa')),
                ('has_transshipment', models.BooleanField(default=False, verbose_name='Com transbordo')),
                ('delivery_window_start', models.DateField(blank=True, null=True, verbose_name='Janela entrega início')),
                ('delivery_window_end', models.DateField(blank=True, null=True, verbose_name='Janela entrega fim')),
                ('participant_product_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo Produto Participante')),
                ('delivered_by_holder', models.BooleanField(default=True, verbose_name='Entregue pelo titular')),
                ('billing_producer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome Produtor Faturamento')),
                ('client_state_registration', models.CharField(blank=True, default='', max_length=30, verbose_name='Inscrição Estadual Cliente')),
                ('cnpj_billing', models.CharField(blank=True, default='', max_length=20, verbose_name='CNPJ Faturamento')),
                ('commercial_responsible_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome Comercial Responsável')),
                ('rfl_value_kg', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Valor pauta RFL (R$/kg)')),
                ('executed_freight_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Vlr frete executado (R$/ton)')),
                ('scheduling', models.CharField(blank=True, default='', max_length=50, verbose_name='Agendamento')),
                ('route_info', models.CharField(blank=True, default='', max_length=100, verbose_name='Percurso')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de liberação')),
                ('base_lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_lot', to='contracts.contractbaselot', verbose_name='Lote Base')),
                ('commercial_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_lots', to='core.commercialresponsible', verbose_name='Comercial Responsável')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_lots', to='core.participant', verbose_name='Participante')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_managed_lots', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por')),
                ('terminal_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_lots', to='core.terminaldestination', verbose_name='Terminal Destino')),
                ('transshipment_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_lots', to='core.transshipmentlocation', verbose_name='Local Transbordo')),
            ],
            options={
                'verbose_name': 'Lote Gerenciado',
                'verbose_name_plural': 'Lotes Gerenciados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Data Upload')),
                ('status', models.CharField(choices=[('processing', 'Em processamento'), ('success', 'Upload com sucesso'), ('error', 'Erro upload')], default='processing', max_length=30, verbose_name='Status')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('file', models.FileField(upload_to='contracts/uploads/%Y/%m/', verbose_name='Arquivo')),
                ('row_count', models.IntegerField(default=0, verbose_name='Linhas processadas')),
                ('error_count', models.IntegerField(default=0, verbose_name='Linhas com erro')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Upload de Contratos',
                'verbose_name_plural': 'Uploads de Contratos',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddField(
            model_name='contractbaselot',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_lots', to='contracts.contractupload', verbose_name='Upload'),
        ),
        migrations.AddIndex(
            model_name='contractbaselot',
            index=models.Index(fields=['lot_number'], name='contracts_c_lot_num_a6553d_idx'),
        ),
        migrations.AddIndex(
            model_name='contractbaselot',
            index=models.Index(fields=['cpf_cnpj'], name='contracts_c_cpf_cnp_614fed_idx'),
        ),
    ]
