# Generated by Django 5.2.1 on 2026-04-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_historicalcontractbaselot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmanagedlot',
            name='has_participant',
            field=models.BooleanField(default=False, verbose_name='Carga com participante'),
        ),
        migrations.AddField(
            model_name='historicalcontractmanagedlot',
            name='has_participant',
            field=models.BooleanField(default=False, verbose_name='Carga com participante'),
        ),
    ]
