# Generated by Django 5.2.1 on 2026-04-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contractmanagedlot_has_participant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmanagedlot',
            name='participant_product_type',
        ),
        migrations.RemoveField(
            model_name='historicalcontractmanagedlot',
            name='participant_product_type',
        ),
    ]
