# Generated by Django 5.2.1 on 2026-04-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_remove_contractmanagedlot_participant_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmanagedlot',
            name='loading_site',
            field=models.CharField(blank=True, default='', help_text='Nome da Fazenda ou Armazém onde será realizado o embarque do produto.', max_length=300, verbose_name='Local Retirada'),
        ),
        migrations.AddField(
            model_name='historicalcontractmanagedlot',
            name='loading_site',
            field=models.CharField(blank=True, default='', help_text='Nome da Fazenda ou Armazém onde será realizado o embarque do produto.', max_length=300, verbose_name='Local Retirada'),
        ),
        migrations.AlterField(
            model_name='contractmanagedlot',
            name='pickup_location',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Cidade Embarque'),
        ),
        migrations.AlterField(
            model_name='historicalcontractmanagedlot',
            name='pickup_location',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Cidade Embarque'),
        ),
    ]
