# Generated by Django 5.2.1 on 2026-04-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contractmanagedlot_loading_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmanagedlot',
            name='route_info',
            field=models.BooleanField(default=False, verbose_name='Percurso: NI'),
        ),
        migrations.AlterField(
            model_name='historicalcontractmanagedlot',
            name='route_info',
            field=models.BooleanField(default=False, verbose_name='Percurso: NI'),
        ),
    ]
