# Generated by Django 5.2.1 on 2026-04-27 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_alter_contractmanagedlot_route_info_and_more'),
        ('core', '0004_tipofretesaida_historicaltipofretesaida'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmanagedlot',
            name='collection_point_code',
            field=models.CharField(blank=True, default='', help_text='Código fornecedor SAP do local de carregamento (buscar na XK03 pela inscrição estadual).', max_length=50, verbose_name='Código Ponto de Coleta'),
        ),
        migrations.AddField(
            model_name='contractmanagedlot',
            name='freight_type_exit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_lots', to='core.tipofretesaida', verbose_name='Tipo Frete Saída'),
        ),
        migrations.AddField(
            model_name='contractmanagedlot',
            name='loading_state_registration',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Inscrição Estadual Carregamento'),
        ),
        migrations.AddField(
            model_name='historicalcontractmanagedlot',
            name='collection_point_code',
            field=models.CharField(blank=True, default='', help_text='Código fornecedor SAP do local de carregamento (buscar na XK03 pela inscrição estadual).', max_length=50, verbose_name='Código Ponto de Coleta'),
        ),
        migrations.AddField(
            model_name='historicalcontractmanagedlot',
            name='freight_type_exit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tipofretesaida', verbose_name='Tipo Frete Saída'),
        ),
        migrations.AddField(
            model_name='historicalcontractmanagedlot',
            name='loading_state_registration',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Inscrição Estadual Carregamento'),
        ),
    ]
