# Generated by Django 5.2.1 on 2026-04-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contractmanagedlot_collection_point_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmanagedlot',
            name='freight_agent',
            field=models.CharField(blank=True, default='', help_text='Código do agente/transportadora. CIF → transportadora da filial; FOB → código ponto de coleta; CPT → seleção manual.', max_length=100, verbose_name='Agente Frete'),
        ),
        migrations.AddField(
            model_name='historicalcontractmanagedlot',
            name='freight_agent',
            field=models.CharField(blank=True, default='', help_text='Código do agente/transportadora. CIF → transportadora da filial; FOB → código ponto de coleta; CPT → seleção manual.', max_length=100, verbose_name='Agente Frete'),
        ),
    ]
