# Generated by Django 5.2.1 on 2026-05-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_fix_historical_route_info_null'),
        ('core', '0007_exitfreighttype_historicalexitfreighttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmanagedlot',
            name='freight_type_exit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_lots', to='core.exitfreighttype', verbose_name='Tipo Frete Saída'),
        ),
        migrations.AlterField(
            model_name='historicalcontractmanagedlot',
            name='freight_type_exit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.exitfreighttype', verbose_name='Tipo Frete Saída'),
        ),
    ]
