# Generated by Django 5.2.1 on 2026-05-05 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_alter_contractmanagedlot_freight_type_exit_and_more'),
        ('core', '0009_exitfreighttype_descriptions_managedlot_billing_branch_nf'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmanagedlot',
            name='billing_branch',
            field=models.ForeignKey(blank=True, help_text='Filial que emitirá as Ordens de Venda para este lote.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_lot_billing', to='core.branch', verbose_name='Filial Emissora da Ordem'),
        ),
        migrations.AddField(
            model_name='contractmanagedlot',
            name='has_nf_future_delivery',
            field=models.BooleanField(default=False, verbose_name='NF Entrega Futura?'),
        ),
        migrations.AddField(
            model_name='contractmanagedlot',
            name='nf_key_future_delivery',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Chave NF Entrega Futura'),
        ),
        migrations.AddField(
            model_name='historicalcontractmanagedlot',
            name='billing_branch',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Filial que emitirá as Ordens de Venda para este lote.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.branch', verbose_name='Filial Emissora da Ordem'),
        ),
        migrations.AddField(
            model_name='historicalcontractmanagedlot',
            name='has_nf_future_delivery',
            field=models.BooleanField(default=False, verbose_name='NF Entrega Futura?'),
        ),
        migrations.AddField(
            model_name='historicalcontractmanagedlot',
            name='nf_key_future_delivery',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Chave NF Entrega Futura'),
        ),
    ]
