# Generated by Django 5.2.1 on 2026-05-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_exitfreighttype_descriptions_managedlot_billing_branch_nf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmanagedlot',
            name='status',
            field=models.CharField(choices=[('awaiting_request', 'Aguardando solicitação de embarque'), ('awaiting_approval', 'Aguardando liberação'), ('in_progress', 'Embarque em andamento'), ('finished', 'Embarque Finalizado'), ('cancelled', 'Cancelado'), ('awaiting_change_quantity', 'Aguardando atualização de quantidade')], default='awaiting_request', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalcontractmanagedlot',
            name='status',
            field=models.CharField(choices=[('awaiting_request', 'Aguardando solicitação de embarque'), ('awaiting_approval', 'Aguardando liberação'), ('in_progress', 'Embarque em andamento'), ('finished', 'Embarque Finalizado'), ('cancelled', 'Cancelado'), ('awaiting_change_quantity', 'Aguardando atualização de quantidade')], default='awaiting_request', max_length=30, verbose_name='Status'),
        ),
    ]
