# Generated by Django 5.2.1 on 2026-05-11 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_salesorder_rpa_traceback_managedlot_awaiting_change_qty'),
        ('core', '0010_alter_exitfreighttype_incoterm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmanagedlot',
            name='collection_point_code',
            field=models.CharField(default='', help_text='Código fornecedor SAP do local de carregamento (buscar na XK03 pela inscrição estadual).', max_length=50, verbose_name='Código Ponto de Coleta'),
        ),
        migrations.AlterField(
            model_name='contractmanagedlot',
            name='freight_type_exit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_lots', to='core.exitfreighttype', verbose_name='Tipo Frete Saída'),
        ),
        migrations.AlterField(
            model_name='historicalcontractmanagedlot',
            name='collection_point_code',
            field=models.CharField(default='', help_text='Código fornecedor SAP do local de carregamento (buscar na XK03 pela inscrição estadual).', max_length=50, verbose_name='Código Ponto de Coleta'),
        ),
    ]
