# Generated by Django 5.2.1 on 2026-04-22 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado')], default='pending', max_length=30, verbose_name='Status')),
                ('desk_manager_ticket_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Ticket Desk Manager')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('managed_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_requests', to='contracts.contractmanagedlot', verbose_name='Lote')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Solicitação de Embarque',
                'verbose_name_plural': 'Solicitações de Embarque',
                'ordering': ['-requested_at'],
            },
        ),
    ]
