# Generated by Django 5.2.1 on 2026-05-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_historicalshipmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipmentrequest',
            name='harvest_year',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Safra'),
        ),
        migrations.AddField(
            model_name='shipmentrequest',
            name='harvest_year',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Safra'),
        ),
    ]
